/**
 * S3 Stack — MedSlot
 *
 * Defines 3 S3 buckets:
 *   - medslot-records:       Patient health record uploads; SSE-S3; Block Public Access
 *   - medslot-prescriptions: Generated prescription PDFs; SSE-S3; Block Public Access
 *   - medslot-credentials:   Doctor registration credential documents; SSE-S3; Block Public Access
 *
 * CORS policy on the records bucket allows presigned PUT from the frontend origin.
 * No public access on any bucket — all access via presigned URLs generated by the API.
 *
 * Full implementation is delivered in TASK-006 (AWS CDK Infrastructure Stack).
 * This file is the scaffold stub created in TASK-001.
 */

import * as cdk from 'aws-cdk-lib/core';
import { Construct } from 'constructs';

export class S3Stack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Full S3 bucket implementation in TASK-006.
  }
}
