/**
 * s3-stack.ts — MedSlot S3 Buckets & Secrets Manager (TASK-006)
 *
 * S3 Buckets (all with SSE-S3 + Block Public Access):
 *   medslot-records-{account}-{region}       — Patient health record uploads
 *     → CORS policy for presigned PUT from frontend (client-direct upload)
 *   medslot-prescriptions-{account}-{region} — Generated prescription PDFs
 *     → Server-side only; no CORS needed
 *   medslot-credentials-{account}-{region}   — Doctor MCI registration documents
 *     → Server-side only; no CORS needed
 *
 * Secrets Manager entries (placeholder values; rotated/updated at deploy time):
 *   medslot/jwt/secret            — JWT HS256 signing secret
 *   medslot/otp/pepper            — OTP SHA-256 PEPPER
 *   medslot/msg91/api-key         — MSG91 OTP SMS API key
 *   medslot/sendgrid/api-key      — SendGrid transactional email API key
 *   medslot/razorpay/keys         — Razorpay key ID, secret, webhook secret
 *
 * Architecture principles enforced:
 *   - enforceSSL: true → denies unencrypted HTTP uploads (NFR-SEC-001)
 *   - Block Public Access ALL → all object access via presigned URL only (NFR-SEC-008)
 *   - SSE-S3 default encryption → all objects encrypted at rest (NFR-SEC-003)
 *   - RETAIN policy → medical data never auto-deleted (10-year retention BR-022)
 *
 * ADR references: ADR-003 (S3 presigned PUT client-direct upload)
 * NFR references: NFR-SEC-003, NFR-SEC-008, NFR-PE-005
 */

import * as cdk from 'aws-cdk-lib/core';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export class S3Stack extends cdk.Stack {
  /** Health records bucket — consumed by EcsStack for IAM policy attachment */
  public readonly recordsBucket: s3.Bucket;

  /** Prescription PDFs bucket — consumed by EcsStack */
  public readonly prescriptionsBucket: s3.Bucket;

  /** Doctor credential documents bucket — consumed by EcsStack */
  public readonly credentialsBucket: s3.Bucket;

  // Secrets Manager secrets — consumed by EcsStack to grant ECS task role read access
  public readonly jwtSecret: secretsmanager.Secret;
  public readonly otpPepperSecret: secretsmanager.Secret;
  public readonly msg91Secret: secretsmanager.Secret;
  public readonly sendgridSecret: secretsmanager.Secret;
  public readonly razorpaySecret: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // CORS origins for the health records bucket presigned PUT policy.
    // Override at deploy time via: cdk deploy --context corsOrigins='["https://myorigin.com"]'
    // Default: production and staging origins. Wildcard is never permitted.
    const corsOrigins: string[] = this.node.tryGetContext('corsOrigins') ?? [
      'https://medslot.in',
      'https://staging.medslot.in',
    ];

    // ── Shared bucket configuration ────────────────────────────────────────────
    // All three buckets share these security-critical properties.
    const commonProps: Omit<s3.BucketProps, 'bucketName' | 'cors'> = {
      // SSE-S3 (AES-256) — NFR-SEC-003
      encryption: s3.BucketEncryption.S3_MANAGED,

      // Block all public access — NFR-SEC-008
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,

      // Deny unencrypted (HTTP) uploads via bucket policy — NFR-SEC-001
      enforceSSL: true,

      // Medical data retention: RETAIN to prevent accidental deletion (BR-022)
      removalPolicy: cdk.RemovalPolicy.RETAIN,

      // No versioning: objects use UUID keys (idempotent, never overwritten)
      versioned: false,
    };

    // ── Health Records Bucket ──────────────────────────────────────────────────
    // CORS policy allows the browser to PUT directly to S3 using a presigned URL
    // generated by the Django API. File bytes never transit through the API server
    // — meets NFR-PE-005 (≤5s P95 upload for 10MB files). ADR-003.
    //
    // corsOrigins is read from CDK context (see above) — no wildcard permitted.
    // Pass --context corsOrigins='["https://myenv.example.com"]' at deploy time
    // to override for non-standard environments.
    this.recordsBucket = new s3.Bucket(this, 'RecordsBucket', {
      ...commonProps,
      bucketName: `medslot-records-${this.account}-${this.region}`,
      cors: [
        {
          allowedMethods: [s3.HttpMethods.PUT],
          allowedOrigins: corsOrigins,
          allowedHeaders: ['*'],
          exposedHeaders: ['ETag'],
          maxAge: 3000,
        },
      ],
    });

    // ── Prescription PDFs Bucket ───────────────────────────────────────────────
    // Celery worker uploads PDFs server-side — no CORS required.
    // Presigned GET URLs (7-day expiry) are generated by the API on demand.
    this.prescriptionsBucket = new s3.Bucket(this, 'PrescriptionsBucket', {
      ...commonProps,
      bucketName: `medslot-prescriptions-${this.account}-${this.region}`,
    });

    // ── Doctor Credentials Bucket ──────────────────────────────────────────────
    // Admin reviews uploaded MCI registration documents — server-side access only.
    this.credentialsBucket = new s3.Bucket(this, 'CredentialsBucket', {
      ...commonProps,
      bucketName: `medslot-credentials-${this.account}-${this.region}`,
    });

    // ── AWS Secrets Manager ────────────────────────────────────────────────────
    // All application secrets live in Secrets Manager, never in environment
    // variables baked into container images. ECS task roles are granted
    // secretsmanager:GetSecretValue for their specific secrets in EcsStack.
    //
    // Secrets without generateSecretString are created as empty placeholders
    // (third-party API keys are set manually via AWS Console or CLI before
    // first deployment). Secrets with generateSecretString auto-generate
    // cryptographically random values.

    // JWT HS256 signing secret — 64-byte random string
    this.jwtSecret = new secretsmanager.Secret(this, 'JwtSecret', {
      secretName: 'medslot/jwt/secret',
      description: 'JWT HS256 signing secret — used by Django simplejwt',
      generateSecretString: {
        passwordLength: 64,
        excludePunctuation: false,
        includeSpace: false,
        secretStringTemplate: JSON.stringify({ type: 'jwt_secret' }),
        generateStringKey: 'value',
      },
    });

    // OTP SHA-256 PEPPER — adds entropy to stored OTP hashes beyond the code itself
    this.otpPepperSecret = new secretsmanager.Secret(this, 'OtpPepperSecret', {
      secretName: 'medslot/otp/pepper',
      description: 'OTP SHA-256 PEPPER — hardens stored OTP hashes (see accounts/services.py)',
      generateSecretString: {
        passwordLength: 64,
        excludePunctuation: false,
        includeSpace: false,
        secretStringTemplate: JSON.stringify({ type: 'otp_pepper' }),
        generateStringKey: 'value',
      },
    });

    // MSG91 API key — set manually before first deployment
    this.msg91Secret = new secretsmanager.Secret(this, 'Msg91ApiKey', {
      secretName: 'medslot/msg91/api-key',
      description: 'MSG91 v5 API key for OTP SMS delivery (set manually)',
    });

    // SendGrid API key — set manually before first deployment
    this.sendgridSecret = new secretsmanager.Secret(this, 'SendgridApiKey', {
      secretName: 'medslot/sendgrid/api-key',
      description: 'SendGrid v3 API key for transactional email (set manually)',
    });

    // Razorpay credentials — key_id, key_secret, webhook_secret bundled in one secret
    this.razorpaySecret = new secretsmanager.Secret(this, 'RazorpayKeys', {
      secretName: 'medslot/razorpay/keys',
      description:
        'Razorpay key_id, key_secret, and webhook_secret for doctor subscription billing',
    });

    // ── CloudFormation Outputs ─────────────────────────────────────────────────
    new cdk.CfnOutput(this, 'RecordsBucketName', {
      value: this.recordsBucket.bucketName,
      description: 'Health records S3 bucket name',
      exportName: `${this.stackName}-RecordsBucketName`,
    });
    new cdk.CfnOutput(this, 'PrescriptionsBucketName', {
      value: this.prescriptionsBucket.bucketName,
      description: 'Prescription PDFs S3 bucket name',
      exportName: `${this.stackName}-PrescriptionsBucketName`,
    });
    new cdk.CfnOutput(this, 'CredentialsBucketName', {
      value: this.credentialsBucket.bucketName,
      description: 'Doctor credentials S3 bucket name',
      exportName: `${this.stackName}-CredentialsBucketName`,
    });
    new cdk.CfnOutput(this, 'JwtSecretArn', {
      value: this.jwtSecret.secretArn,
      description: 'JWT secret ARN (read by ECS task role)',
      exportName: `${this.stackName}-JwtSecretArn`,
    });
  }
}
